version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
    #expose the Minecraft server port outside of container
    - "25565:25565"
    #add rcon port for command execution
    #login to RCON using
    #mcrcon -H ip_address -P 25575 -p password
    - "25575:25575"
    #If you want to use RCON make sure these options are set properly
    #enable-rcon=true
    #rcon.port=25575
    #rcon.password=your_password
    environment:
      #REQUIRED for all types
      EULA: "TRUE"
      MEMORY: "7G"
      #Set server type (vs the default of vanilla)
      TYPE: FORGE
      VERSION: 1.20.1
      ENABLE_ROLLING_LOGS: "true"
      #MODS_FILE: /extras/mods.txt
    volumes:
    #use a named, managed volume for data volume
    - ./data:/data
      #- ./mods.txt:/extras/mods.txt:ro
    #attach local host directory "mods" in same directory as this compose file
    #all mods in this directory get copied into /data/mods at startup

volumes:
  # eclared the named volume, but use default/local storage engine
  mc_forge: {}
