
[Drinks]
	#Defines items that will recover thirst when drunk
	#Format: [["item-id-1", hydration-amount, quenching-amount], ["item-id-2", hydration-amount, quenching-amount], ...etc]
	drinks = [
["cold_sweat:filled_waterskin", 10, 12],
["minecraft:potion", 6, 8], 
["thirst:terracotta_water_bowl", 4, 5], 
["farmersrespite:green_tea", 10, 14], 
["farmersrespite:yellow_tea", 10, 14], 
["farmersrespite:black_tea", 10, 14], 
["farmersrespite:rose_hip_tea", 12, 22], 
["farmersrespite:dandelion_tea", 12, 22], 
["farmersrespite:coffee", 6, 11], 
["create:builders_tea", 12, 22],
["ends_delight:chorus_fruit_wine", 10, 14], 
["italian_delight:sweet_berry_wine", 10, 14], 
["italian_delight:glowberry_wine", 10, 14], 
["italian_delight:rosewine", 10, 14], 
["italian_delight:hasting_potion", 10, 14], 
["italian_delight:hellhound_wine", 10, 14], 
["italian_delight:dragonborn_wine", 10, 14], 
["italian_delight:prewine_substance", 5, 7], 
["twilightdelight:thorn_rose_tea", 10, 16],
["twilightdelight:glacier_ice_tea", 10, 18],
["fruitsdelight:mangosteen_tea", 10, 18],
["fruitsdelight:lychee_cherry_tea", 10, 18],
["fruitsdelight:peach_tea", 10, 18],
["fruitsdelight:mango_tea", 10, 18],
["fruitsdelight:hawberry_tea", 10, 18],
["farmersrespite:gamblers_tea", 10, 18],
["farmersrespite:purulent_tea", 10, 18],
["farmersdelightplus:cactus_tea", 10, 18],
["extradelight:mint_tea", 10, 18],
["extradelight:ginger_tea", 10, 18],
["extradelight:corn_silk_tea", 10, 18],
["ends_delight:bubble_tea", 10, 18],
["ends_delight:chorus_fruit_milk_tea", 10, 18],
["aetherdelight:aetherflower_tea", 10, 18],
["farmersdelightplus:miners_drink", 10, 18],
["twilightdelight:tear_drink", 10, 18],
["extradelight:chocolate_milk", 16, 4],
["minecraft:milk_bucket", 10, 20],
["farmersdelight:milk_bottle", 6, 10],
["crabbersdelight:kelp_shake", 16, 4],
["extradelight:milkshake", 16, 4],
["extradelight:chocolate_milkshake", 16, 4],
["extradelight:glow_berry_milkshake", 16, 4],
["extradelight:sweet_berry_milkshake", 16, 4],
["extradelight:pumpkin_milkshake", 16, 4],
["extradelight:honey_milkshake", 16, 4],
["extradelight:apple_milkshake", 16, 4],
["extradelight:cookie_dough_milkshake", 16, 4],
["extradelight:mint_chip_milkshake", 16, 4],
["fruitsdelight:mango_milkshake", 16, 4], 
["farmersdelight:apple_cider", 8, 13], 
["extradelight:glow_berry_juice", 8, 13],
["extradelight:sweet_berry_juice", 8, 13],
["extradelight:tomato_juice", 8, 13],
["extradelight:cactus_juice", 8, 13],
["farmersdelightplus:chilled_sweet_berry_juice", 8, 13],
["farmersdelightplus:berry_compote", 8, 13],
["fruitsdelight:hamimelon_juice", 8, 13],
["fruitsdelight:orange_juice", 8, 13],
["fruitsdelight:lemon_juice", 8, 13],
["fruitsdelight:pear_juice", 8, 13],
["fruitsdelight:kiwi_juice", 8, 13],
["fruitsdelight:bayberry_soup", 8, 13],
["twilightdelight:torchberry_juice", 8, 13],
["twilightdelight:phytochemical_juice", 8, 13], 
["farmersdelight:melon_juice", 8, 13], 
["extradelight:ginger_beer", 10, 14], 
["brewinandchewin:beer", 10, 14], 
["brewinandchewin:vodka", 10, 14], 
["brewinandchewin:rice_wine", 10, 14], 
["brewinandchewin:mead", 10, 14], 
["brewinandchewin:egg_grog", 10, 14], 
["brewinandchewin:glittering_grenadine", 10, 14], 
["brewinandchewin:bloody_mary", 12, 22], 
["brewinandchewin:salty_folly", 12, 22], 
["brewinandchewin:pale_jane", 12, 22], 
["brewinandchewin:saccharine_rum", 12, 22], 
["brewinandchewin:strongroot_ale", 12, 22], 
["brewinandchewin:dread_nog", 12, 22], 
["brewinandchewin:kombucha", 14, 22], 
["brewinandchewin:red_rum", 14, 22], 
["brewinandchewin:steel_toe_stout", 14, 22], 
["collectorsreap:pink_limeade", 8, 10], 
["collectorsreap:berry_limeade", 8, 13], 
["collectorsreap:limeade", 8, 13], 
["collectorsreap:pink_limeade", 8, 13], 
["collectorsreap:pomegranate_black_tea", 10, 14], 
["collectorsreap:lime_green_tea", 10, 14], 
["toughasnails:dirty_water_bottle", 6, 8], 
["toughasnails:purified_water_bottle", 8, 10], 
["toughasnails:dirty_water_canteen", 8, 10], 
["toughasnails:water_canteen", 9, 11], 
["toughasnails:purified_water_canteen", 10, 12], 
["toughasnails:melon_juice", 8, 13], 
["toughasnails:apple_juice", 8, 13], 
["toughasnails:cactus_juice", 8, 13], 
["toughasnails:carrot_juice", 8, 13], 
["toughasnails:glow_berry_juice", 8, 13], 
["toughasnails:chorus_fruit_juice", 8, 13], 
["toughasnails:suspicious_water_cup", 8, 13], 
["toughasnails:pumpkin_juice", 8, 13], 
["toughasnails:sweet_berry_juice", 8, 13]]

[Foods]
	#Defines items that will recover thirst when eaten
	#Format: [["item-id-1", hydration-amount, quenching-amount], ["item-id-2", hydration-amount, quenching-amount], ...etc]
	foods = [
    ["minecraft:apple", 2, 3], 
    ["fruitsdelight:pear", 2, 3],
    ["fruitsdelight:mango", 2, 3],
    ["fruitsdelight:hamimelon_slice", 2, 3],
    ["fruitsdelight:pineapple_slice", 2, 3],
    ["fruitsdelight:lemon", 2, 3],
    ["fruitsdelight:lychee", 2, 3],
    ["fruitsdelight:kiwi", 2, 3],
    ["fruitsdelight:orange", 3, 4],
    ["fruitsdelight:peach", 3, 4],
    ["minecraft:golden_apple", 2, 3], 
    ["minecraft:enchanted_golden_apple", 2, 3], 
    ["minecraft:melon_slice", 4, 5], 
    ["minecraft:carrot", 1, 2], 
    ["minecraft:mushroom_stew", 2, 3], 
    ["minecraft:rabbit_stew", 2, 3], 
    ["minecraft:beetroot_soup", 5, 7], 
    ["minecraft:beetroot", 1, 2], 
    ["minecraft:sweet_berries", 1, 2], 
    ["minecraft:glow_berries", 1, 2], 
    ["aether:blue_berry", 1, 2], 
    ["aether:enchanted_berry", 2, 4], 
    ["fruitsdelight:cranberry", 1, 2], 
    ["fruitsdelight:blueberry", 1, 2], 
    ["fruitsdelight:hawberry", 1, 2], 
    ["fruitsdelight:bayberry", 1, 2], 
    ["minecraft:golden_carrot", 1, 2], 
    ["farmersdelight:pumpkin_slice", 2, 1], 
    ["farmersdelight:cabbage_leaf", 1, 2], 
    ["farmersdelight:melon_popsicle", 7, 9], 
    ["farmersdelight:fruit_salad", 6, 8], 
    ["farmersdelight:tomato_sauce", 4, 5], 
    ["farmersdelight:mixed_salad", 4, 5], 
    ["farmersdelight:beef_stew", 4, 5], 
    ["farmersdelight:chicken_soup", 4, 5], 
    ["farmersdelight:vegetable_soup", 4, 5], 
    ["farmersdelight:fish_stew", 4, 5], 
    ["farmersdelight:pumpkin_soup", 4, 5], 
    ["farmersdelight:baked_cod_stew", 4, 5], 
    ["farmersdelight:noodle_soup", 4, 5], 
    ["aetherdelight:quail_stew", 4, 5], 
    ["alexsdelight:kangaroo_stew", 4, 5], 
    ["aquaculturedelight:bass_stew", 4, 5], 
    ["ends_delight:enderman_gristle_stew", 4, 5], 
    ["ends_delight:dragon_meat_stew", 4, 5], 
    ["extradelight:pork_stew", 4, 5], 
    ["extradelight:lamb_stew", 4, 5], 
    ["extradelight:chicken_stew", 4, 5], 
    ["extradelight:stewed_apples", 4, 5], 
    ["extradelight:goat_stew", 4, 5], 
    ["fruitsdelight:fig_chicken_stew", 4, 5], 
    ["mynethersdelight:strider_stew", 4, 5], 
    ["mynethersdelight:spicy_hoglin_stew", 4, 5], 
    ["twilightdelight:glowstew", 4, 5], 
    ["twilightdelight:thousand_plant_stew", 4, 5], 
    ["alexsmobs:sopa_de_macaco", 4, 5], 
    ["farmersdelight:bone_broth", 4, 5], 
    ["aetherdelight:sweet_and_sour_soup", 4, 5], 
    ["alexsdelight:acacia_blossom_soup", 4, 5], 
    ["aquaculture:turtle_soup", 4, 5], 
    ["aquaculturedelight:unusual_fish_soup", 4, 5], 
    ["brewinandchewin:creamy_onion_soup", 4, 5], 
    ["ends_delight:dragon_breath_and_chorus_soup", 4, 5], 
    ["twilightdelight:borer_tear_soup",4,5],
    ["ends_delight:shulker_soup",4,5],
    ["extradelight:potato_soup",4,5],
    ["extradelight:tomato_soup",4,5],
    ["extradelight:fish_soup",4,5],
    ["extradelight:carrot_soup",4,5],
    ["extradelight:oxtail_soup",4,5],
    ["extradelight:cactus_soup",4,5],
    ["farmersdelightplus:turtle_soup",4,5],
    ["farmersdelightplus:pho_soup",4,5],
    ["moredelight:carrot_soup",4,5],
    ["mynethersdelight:spicy_noodle_soup",4,5],
    ["mynethersdelight:rock_soup",4,5],
    ["naturalistdelight:duck_soup",4,5],
    ["tconstruct:meat_soup",4,5],
    ["collectorsreap:lime_slice", 1, 2], 
    ["collectorsreap:lime", 2, 3], 
    ["collectorsreap:portobello_rice_soup", 6, 8], 
    ["collectorsreap:lime_popsicle", 7, 9]]

[Blacklist]
	#A mod may have added thirst compatibility to an item via code. If you want to edit the thirst values
	#of that item, add an entry in one of the first two lists. If instead you want to remove thirst support for that item, add an entry in this list
	#Format: ["examplemod:example_item_1", "examplemod:example_item_2"]
	itemsBlacklist = []

