version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:java8-jdk
    environment:
      EULA: "true"
      TYPE: FORGE
      VERSION: "1.12.2"
      FORGE_VERSION: "14.23.5.2860"
      FORGE_FORCE_REINSTALL: "true"
      REMOVE_OLD_MODS: "true"
      MODS_FILE: /extras/mods.txt
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
      - ./mods.txt:/extras/mods.txt:ro


volumes:
  data:
