- name: Setup Prometheus 
  hosts: slave
  tasks:
    - name: Clone the shellfish repository
      git:
        repo: https://github.com/Talandar99/shellfish.git
        dest: ~/shellfish

    - name: Run the prometheus_monitoring_full_setup_slave_daemon.sh script
      command: ./prometheus_monitoring_full_setup_slave_daemon.sh
      args:
        chdir: ~/shellfish/prometheus_docker/
      ignore_errors: true
      register: script_result

    - name: check if script ran successfully
      fail:
        msg: "Script execution failed: {{ script_result.stderr }}"
      when: script_result.rc != 0

