
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [
        ["minecraft:the_nether", 1.0, "MC"], 
        ["minecraft:the_end", -0.1, "MC"]
    ]
	#Defines the temperature of a dimension, overriding all other biome and dimension temperatures/settings
	"Dimension Temperatures" = [
        ["aether:the_aether", 10,"C"],
        ["twilightforest:twilight_forest", 25,"C"]
    ]

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding the biome's default temperature
	"Biome Temperatures" = [
        #cold nether biomes
        #["minecraft:soul_sand_valley", 53.0, 53.0, "F"], 
        ["minecraft:soul_sand_valley", 8.0, 8.0, "C"], 
        ["incendium:quartz_flats", 8.0, 8.0, "C"], 
        #other
        ["minecraft:old_growth_spruce_taiga", 48.0, 62.0, "F"], 
        ["terralith:birch_taiga", 40.0, 62.0, "F"], 
        ["minecraft:taiga", 44.0, 62.0, "F"], 
        ["terralith:lavender_valley", 59.0, 76.0, "F"], 
        ["terralith:arid_highlands", 74.0, 102.0, "F"], 
        ["minecraft:old_growth_birch_forest", 58.0, 72.0, "F"], 
        ["terralith:desert_canyon", 73.0, 121.0, "F"], 
        ["terralith:bryce_canyon", 72.0, 110.0, "F"], 
        ["terralith:alpine_grove", 16.0, 53.0, "F"], 
        ["minecraft:deep_dark", 63.0, 63.0, "F"], 
        ["terralith:steppe", 44.0, 78.0, "F"], 
        ["terralith:volcanic_crater", 96.0, 162.0, "F"], 
        ["terralith:amethyst_rainforest", 69.0, 84.0, "F"], 
        ["terralith:lavender_forest", 56.0, 75.0, "F"], 
        ["terralith:caldera", 58.0, 71.0, "F"], 
        ["minecraft:eroded_badlands", 88.0, 120.0, "F"], 
        ["minecraft:snowy_beach", 38.0, 52.0, "F"], 
        ["terralith:fractured_savanna", 65.0, 92.0, "F"], 
        ["terralith:yellowstone", 47.0, 68.0, "F"], 
        ["terralith:forested_highlands", 43.0, 70.0, "F"], 
        ["minecraft:river", 60.0, 70.0, "F"], 
        ["terralith:shield_clearing", 28.0, 80.0, "F"], 
        ["minecraft:deep_frozen_ocean", 56.0, 65.0, "F"], 
        ["minecraft:snowy_slopes", 24.0, 38.0, "F"], 
        ["terralith:blooming_plateau", 49.0, 78.0, "F"], 
        ["minecraft:snowy_taiga", 19.0, 48.0, "F"], 
        ["terralith:shield", 48.0, 68.0, "F"], 
        ["terralith:warped_mesa", 66.0, 84.0, "F"], 
        ["terralith:desert_spires", 60.0, 121.0, "F"], 
        ["minecraft:savanna_plateau", 76.0, 98.0, "F"], 
        ["minecraft:jungle", 76.0, 87.0, "F"], 
        ["terralith:brushland", 64.0, 89.0, "F"], 
        ["terralith:volcanic_peaks", 76.0, 122.0, "F"], 
        ["terralith:rocky_mountains", 45.0, 73.0, "F"], 
        ["minecraft:wooded_badlands", 80.0, 108.0, "F"], 
        ["minecraft:windswept_savanna", 67.0, 90.0, "F"], 
        ["minecraft:warm_ocean", 67.0, 76.0, "F"], 
        ["minecraft:desert", 48.0, 115.0, "F"], 
        ["terralith:cloud_forest", 38.0, 58.0, "F"], 
        ["minecraft:frozen_peaks", 15.0, 33.0, "F"], 
        ["terralith:basalt_cliffs", 76.0, 122.0, "F"], 
        ["minecraft:badlands", 84.0, 120.0, "F"], 
        ["minecraft:bamboo_jungle", 76.0, 87.0, "F"], 
        ["terralith:highlands", 62.0, 74.0, "F"], 
        ["terralith:savanna_badlands", 68.0, 99.0, "F"], 
        ["terralith:red_oasis", 58.0, 94.0, "F"], 
        ["minecraft:savanna", 70.0, 95.0, "F"], 
        ["minecraft:old_growth_pine_taiga", 48.0, 62.0, "F"], 
        ["terralith:sandstone_valley", 78.0, 114.0, "F"], 
        ["terralith:moonlight_valley", 57.0, 76.0, "F"], 
        ["minecraft:stony_shore", 50.0, 64.0, "F"], 
        ["terralith:temperate_highlands", 54.0, 80.0, "F"], 
        ["minecraft:swamp", 72.0, 84.0, "F"], 
        ["minecraft:windswept_forest", 48.0, 66.0, "F"], 
        ["terralith:orchid_swamp", 62.0, 81.0, "F"], 
        ["terralith:haze_mountain", 62.0, 74.0, "F"], 
        ["terralith:granite_cliffs", 65.0, 85.0, "F"], 
        ["terralith:ancient_sands", 83.0, 130.0, "F"]
    ]

[Blocks]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: The temperature of the block, in Minecraft units
	#*falloff: The block is less effective as distance increases
	#*max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	#*predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
	#- (Multipl
	#*nbt: The NBT data that the block must have for the temperature to be applied.
	#*temperature-limit: The maximum world temperature at which this block temp will be effective.
	#- (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [
        #create
        ["create:blaze_burner",                 0.6,    7,      1.8,        "",                 "{fuelLevel: 2}"    ], 
        #farmers delight
        ["ends_delight:end_stove",              0.27,   6,      0.5,        "lit=true",         "",                 4], 
        ["farmersdelight:stove",                0.27,   6,      0.5,        "lit=true",         "",                 4], 
        ["mynethersdelight:nether_stove",       -0.27,  6,      0.5,        "lit=true",         "",                 0], 
        ["twilightdelight:maze_stove",          0.27,   6,      0.5,        "lit=true",         "",                 4], 
        ["twilightdelight:fiery_cooking_pot",   0.27,   6,      0.5,        "lit=true",         "",                 4], 
        #twilightforest
        ["twilightforest:fiery_block",          0.25,   3,      1.0,                                                 ], 
        #tinkers
        ["tconstruct:seared_heater",            0.476,  7,      0.9,        "active=true",      ""                  ], 
        ["tconstruct:foundry_controller",       0.476,  7,      0.9,        "active=true",      ""                  ], 
        ["tconstruct:smeltery_controller",      0.476,  7,      0.9,        "active=true",      ""                  ], 
        ["tconstruct:blazewood",                0.25,   3,      0.5,                                                ], 
        #malum
        ["malum:blazing_quartz_ore",            0.15,   3,      0.3,                                                ], 
        ["malum:block_of_blazing_quartz",       0.25,   3,      0.5,                                                ], 
        #aether
        ["aether:icestone",                     -0.35,  7,      1.4,        "",                 "{}",               -1],
        ["ascended_quark:icestone_bricks",      -0.35,  7,      1.4,        "",                 "{}",               -1],
        ["ascended_quark:polished_icestone",    -0.35,  7,      1.4,        "",                 "{}",               -1],
        ["aether:cold_aercloud",                -0.4,   1,      0.8,        "",                 "{}",               -1], 
        #ice and fire
        ["iceandfire:dragon_ice",               -0.35,  5,      1.4,        "",                 "{}",               -0.7],
        #cold_sweat changed
        ["cold_sweat:boiler",                   0.35,   7,      0.9,        "lit=true",         "",                 5], 
        ["cold_sweat:icebox",                   -0.35,  7,      0.9,        "frosted=true",     "",                 0], 
        #torches hot
        ["minecraft:torch",                     0.1,    1,      0.2,        "",                 "",                 ], 
        ["minecraft:wall_torch",                0.1,    1,      0.2,        "",                 "",                 ], 
        ["mynethersdelight:powdery_torch",      0.15,   1,      0.2,        "",                 "",                 ], 
        ["mynethersdelight:wall_powdery_torch", 0.15,   1,      0.2,        "",                 "",                 ], 
        ["aether:ambrosium_torch",              0.15,   1,      0.2,        "",                 "",                 ], 
        ["aether:ambrosium_wall_torch",         0.15,   1,      0.2,        "",                 "",                 ], 
        ["tinkers_thinking:stone_torch",        0.1,    1,      0.2,        "",                 "",                 ], 
        ["tinkers_thinking:wall_stone_torch",   0.1,    1,      0.2,        "",                 "",                 ], 
        ["malum:ether_torch",                   0.1,    1,      0.2,        "",                 "",                 ], 
        ["malum:wall_ether_torch",              0.1,    1,      0.2,        "",                 "",                 ], 
        ["malum:iridescent_ether_torch",        0.1,    1,      0.2,        "",                 "",                 ], 
        ["malum:iridescent_wall_ether_torch",   0.1,    1,      0.2,        "",                 "",                 ], 
        #torches cold
        ["minecraft:soul_torch",                -0.1,   2,      0.4,        "",                 "",                 -1], 
        ["minecraft:soul_wall_torch",           -0.1,   2,      0.4,        "",                 "",                 -1], 
        ["iceandfire:dread_torch",              -0.2,   2,      0.4,        "",                 "",                 -1], 
        ["iceandfire:dread_wall_torch",         -0.2,   2,      0.4,        "",                 "",                 -1], 
        #lanterns
        ["minecraft:lantern",                   0.05,   2,      0.15,        "",                 "",                 ], 
        ["minecraft:soul_lantern",              -0.05,  3,      0.15,        "",                 "",                 -1], 
        ["biomancy:bio_lantern_yellow",         0.05,   2,      0.15,        "",                 "",                 ], 
        ["biomancy:bio_lantern_blue",           -0.05,  3,      0.15,        "",                 "",                 -1], 
        #campfires
        ["minecraft:campfire",                  0.476,  7,      1.0,        "lit=true",         "",                 8], 
        ["minecraft:soul_campfire",             -0.476, 7,      1.0,        "lit=true",         "",                 -8], 
        #minecraft
        ["minecraft:fire",                      0.476,  7,      0.9,        "",                 "",                 8], 
        ["minecraft:magma_block",               0.25,   3,      1.0                                                 ], 
        ["minecraft:lava_cauldron",             0.5,    7,      1.5                                                 ], 
        ["#minecraft:ice",                      -0.15,  4,      0.6,        "",                 "",                 -0.7], 
        ["minecraft:ice",                       -0.15,  4,      0.6,        "",                 "{}",               -0.7], 
        ["minecraft:packed_ice",                -0.25,  4,      1.0,        "",                 "{}",               -0.7], 
        ["minecraft:blue_ice",                  -0.35,  5,      1.4,        "",                 "{}",               -0.7],
        ["minecraft:powder_snow",               -0.4,   1,      0.8,        "",                 "{}",               -1], 
        #other
        ["quark:permafrost",                    -0.1,   2,      0.1,        "",                 "{}",               -0.4], 
        ["immersive_weathering:permafrost",     -0.1,   2,      0.1,        "",                 "{}",               -0.4] 
    ]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Check" = true

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 1.0
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65.0, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = ["#comforts:sleeping_bags"]
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

[Hearth]
	#Allows the hearth to automatically turn on/off based on nearby players' temperature
	#If false, the hearth turns on/off by redstone signal
	"Automatic Hearth" = false
	#How effective the hearth is at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 1.0
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = [
        "minecraft:iron_bars", 
        "minecraft:jungle_leaves", 
        "minecraft:oak_leaves", 
        "minecraft:spruce_leaves", 
        "minecraft:dark_oak_leaves", 
        "minecraft:acacia_leaves", 
        "minecraft:birch_leaves", 
        "minecraft:azalea_leaves", 
        "minecraft:flowering_azalea_leaves", 
        "minecraft:mangrove_leaves", 
        "aether:skyroot_leaves", 
        "aether:golden_oak_leaves", 
        "aether:crystal_leaves", 
        "aether:crystal_fruit_leaves", 
        "aether:holiday_leaves", 
        "aether:decorated_holiday_leaves", 
        "twilightforest:rainbow_oak_leaves", 
        "twilightforest:twilight_oak_leaves", 
        "twilightforest:canopy_leaves", 
        "twilightforest:mangrove_leaves", 
        "twilightforest:dark_leaves", 
        "twilightforest:time_leaves", 
        "twilightforest:transformation_leaves", 
        "twilightforest:mining_leaves", 
        "twilightforest:sorting_leaves", 
        "twilightforest:thorn_leaves", 
        "twilightforest:beanstalk_leaves", 
        "twilightdelight:ironwood_leaves", 
        "culturaldelights:avocado_leaves", 
        "culturaldelights:fruiting_avocado_leaves", 
        "tconstruct:earth_slime_leaves", 
        "tconstruct:sky_slime_leaves", 
        "tconstruct:ender_slime_leaves", 
        "malum:soulwood_leaves", 
        "malum:runewood_leaves", 
        "quark:blue_blossom_leaves", 
        "quark:lavender_blossom_leaves", 
        "quark:orange_blossom_leaves", 
        "quark:pink_blossom_leaves", 
        "quark:yellow_blossom_leaves", 
        "quark:red_blossom_leaves", 
        "quark:ancient_leaves", 
        "extradelight:cinnamon_leaves", 
        "fruitsdelight:pear_leaves", 
        "fruitsdelight:hawberry_leaves", 
        "fruitsdelight:lychee_leaves", 
        "fruitsdelight:mango_leaves", 
        "fruitsdelight:persimmon_leaves", 
        "fruitsdelight:peach_leaves", 
        "fruitsdelight:orange_leaves", 
        "fruitsdelight:apple_leaves", 
        "fruitsdelight:mangosteen_leaves", 
        "fruitsdelight:bayberry_leaves", 
        "fruitsdelight:kiwi_leaves", 
        "fruitsdelight:fig_leaves", 
        "fruitsdelight:durian_leaves", 
        "create:encased_fluid_pipe"
    ]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

#Format: [season-start, season-mid, season-end]
#Applied as an offset to the world's temperature
["Season Temperatures"]
	Summer = [0.4, 0.7, 0.4]
	Autumn = [0.2, 0, -0.2]
	Winter = [-0.4, -0.7, -0.4]
	Spring = [-0.2, 0, 0.2]
#   DEFAULT VALUES
#	Summer = [0.4, 0.6, 0.4]
#	Autumn = [0.2, 0, -0.2]
#	Winter = [-0.4, -0.6, -0.4]
#   Spring = [-0.2, 0, 0.2]
