
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_nether", 1.0], ["minecraft:the_end", -0.1]]
	#Overrides existing dimension temperatures & offsets
	#Also overrides temperatures of all biomes in the dimension
	"Dimension Temperatures" = [["aether:the_aether", 10,"C"]]

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding existing biome temperatures & offsets.
	"Biome Temperatures" = [
        ["minecraft:soul_sand_valley", 53, 53, "F"], 
        ["minecraft:old_growth_birch_forest", 58, 72, "F"], 
        ["minecraft:river", 60, 70, "F"], 
        ["minecraft:swamp", 72, 84, "F"], 
        ["minecraft:savanna", 70, 95, "F"], 
        ["minecraft:savanna_plateau", 76, 98, "F"], 
        ["minecraft:windswept_savanna", 67, 90, "F"], 
        ["minecraft:taiga", 44, 62, "F"], 
        ["minecraft:snowy_taiga", 19, 48, "F"], 
        ["minecraft:old_growth_pine_taiga", 48, 62, "F"], 
        ["minecraft:old_growth_spruce_taiga", 48, 62, "F"], 
        ["minecraft:desert", 48, 115, "F"], 
        ["minecraft:stony_shore", 50, 64, "F"], 
        ["minecraft:snowy_beach", 38, 52, "F"], 
        ["minecraft:snowy_slopes", 24, 38, "F"], 
        ["minecraft:windswept_forest", 48, 66, "F"], 
        ["minecraft:frozen_peaks", 15, 33, "F"], 
        ["minecraft:warm_ocean", 67, 76, "F"], 
        ["minecraft:deep_frozen_ocean", 56, 65, "F"], 
        ["minecraft:jungle", 76, 87, "F"], 
        ["minecraft:bamboo_jungle", 76, 87, "F"], 
        ["minecraft:badlands", 84, 120, "F"], 
        ["minecraft:wooded_badlands", 80, 108, "F"], 
        ["minecraft:eroded_badlands", 88, 120, "F"], 
        ["minecraft:deep_dark", 63, 63, "F"], 
        ["terralith:moonlight_valley", 57, 76, "F"], 
        ["terralith:rocky_mountains", 45, 73, "F"], 
        ["terralith:blooming_plateau", 49, 78, "F"], 
        ["terralith:alpine_grove", 16, 53, "F"], 
        ["terralith:yellowstone", 47, 68, "F"], 
        ["terralith:forested_highlands", 43, 70, "F"], 
        ["terralith:temperate_highlands", 54, 80, "F"], 
        ["terralith:amethyst_rainforest", 69, 84, "F"], 
        ["terralith:sandstone_valley", 78, 114, "F"], 
        ["terralith:ancient_sands", 83, 130, "F"], 
        ["terralith:arid_highlands", 74, 102, "F"], 
        ["terralith:volcanic_crater", 96, 162, "F"], 
        ["terralith:volcanic_peaks", 76, 122, "F"], 
        ["terralith:basalt_cliffs", 76, 122, "F"], 
        ["terralith:birch_taiga", 40, 62, "F"], 
        ["terralith:brushland", 64, 89, "F"], 
        ["terralith:bryce_canyon", 72, 110, "F"], 
        ["terralith:caldera", 58, 71, "F"], 
        ["terralith:cloud_forest", 38, 58, "F"], 
        ["terralith:desert_canyon", 73, 121, "F"], 
        ["terralith:desert_spires", 60, 121, "F"], 
        ["terralith:orchid_swamp", 62, 81, "F"], 
        ["terralith:fractured_savanna", 65, 92, "F"], 
        ["terralith:savanna_badlands", 68, 99, "F"], 
        ["terralith:granite_cliffs", 65, 85, "F"], 
        ["terralith:granite_cliffs", 65, 85, "F"], 
        ["terralith:haze_mountain", 62, 74, "F"], 
        ["terralith:highlands", 62, 74, "F"], 
        ["terralith:lavender_valley", 59, 76, "F"], 
        ["terralith:lavender_forest", 56, 75, "F"], 
        ["terralith:red_oasis", 58, 94, "F"], 
        ["terralith:shield", 48, 68, "F"], 
        ["terralith:shield_clearing", 28, 80, "F"], 
        ["terralith:steppe", 44, 78, "F"], 
        ["terralith:warped_mesa", 66, 84, "F"]
]

[Blocks]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:

	#block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: The temperature of the block, in Minecraft units
	#*falloff: The block is less effective as distance increases
	#*max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	#*predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
    #- (Multiple predicates can be used by separating them with commas [i.e. "lit=true,waterlogged=false"])
	#*nbt: The NBT data that the block must have for the temperature to be applied.
	#*temperature-limit: The maximum world temperature at which this block temp will be effective.
	#- (Represents the minimum temp if the block temp is negative)
    # ["cold_sweat:boiler",                   0.27,   7,          0.88,       "lit=true",     "",     4       ], 
    # ["cold_sweat:icebox",                   -0.27,  7,          0.88,       "frosted=true", "",     0       ], 

        #block-id ,                             temp,   falloff,    max_effect, predicates,         nbt,    temp_limit 
	"Block Temperatures" = [
        ["aether:icestone",                     -0.35,  7,          1.4,        "",                 "{}",   -1      ],
        ["ascended_quark:icestone_bricks",      -0.35,  7,          1.4,        "",                 "{}",   -1      ],
        ["ascended_quark:polished_icestone",    -0.35,  7,          1.4,        "",                 "{}",   -1      ],
        ["iceandfire:dragon_ice",               -0.15,  4,          0.6,        "",                 "{}",   -1      ], 
        ["ends_delight:end_stove",              0.27,   6,          0.5,        "lit=true",         "",     4       ], 
        ["farmersdelight:stove",                0.27,   6,          0.5,        "lit=true",         "",     4       ], 
        ["mynethersdelight:nether_stove",       -0.27,  6,          0.5,        "lit=true",         "",     -0.7    ], 
        ["twilightdelight:maze_stove",          0.27,   6,          0.5,        "lit=true",         "",     4       ], 
        ["tconstruct:seared_heater",            0.476,  7,          0.9,        "active=true",      ""              ], 
        ["tconstruct:foundry_controller",       0.476,  7,          0.9,        "active=true",      ""              ], 
        ["tconstruct:smeltery_controller",      0.476,  7,          0.9,        "active=true",      ""              ], 
        ["create_new_age:reactor_rod",          1.50,   7,          20,         "lit=true",         ""              ], 
        ["create_new_age:corium",               5.00,   7,          40,         "",                 ""              ], 
    #["create:blaze_burner",                 0.3,    6,          0.9,        "blaze=SMOULDERING",""              ], #todo
    #["create:blaze_burner",                 0.45,   6,          1.35,       "blaze=KINDLED",    ""              ], #todo
    #["create:blaze_burner",                 0.6,    6,          1.8,        "blaze=SEETHING",   ""              ], #todo
    #["create_new_age:heater",               0.3,    6,          0.9,        "blaze=SMOULDERING",""              ], #todo
    #["create_new_age:heater",               0.45,   6,          1.35,       "blaze=KINDLED",    ""              ], #todo
    #["create_new_age:heater",               0.45,   6,          1.35,       "blaze=kindled",    ""              ], #todo
    #["create_new_age:heater",               0.6,    6,          1.8,        "blaze=SEETHING",   ""              ], #todo
        ["cold_sweat:boiler",                   0.4,    7,          0.9,        "lit=true",         "",     5       ], 
        ["cold_sweat:icebox",                   -0.4,   7,          0.9,        "frosted=true",     "",     0       ], 
        ["minecraft:fire",                      0.476,  7,          0.9,        "",                 "",     8       ], 
        ["#minecraft:campfires",                0.476,  7,          0.9,        "lit=true",         "",     8       ], 
        ["minecraft:magma_block",               0.25,   3,          1.0                                             ], 
        ["minecraft:lava_cauldron",             0.5,    7,          1.5                                             ], 
        ["#minecraft:ice",                      -0.15,  4,          0.6,        "",                 "",     -0.7    ], 
        ["minecraft:ice",                       -0.15,  4,          0.6,        "",                 "{}",   -0.7    ], 
        ["minecraft:packed_ice",                -0.25,  4,          1.0,        "",                 "{}",   -0.7    ], 
        ["minecraft:blue_ice",                  -0.35,  5,          1.4,        "",                 "{}",   -0.7    ]
    ]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Check" = true

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 1.0
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = ["#comforts:sleeping_bags"]
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

[Hearth]
	#Allows the hearth to automatically turn on/off based on nearby players' temperature
	#If false, the hearth turns on/off by redstone signal
	"Automatic Hearth" = false
	#How effective the hearth is at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 1.0
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "#minecraft:leaves", "create:encased_fluid_pipe"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

#Format: [season-start, season-mid, season-end]
#Applied as an offset to the world's temperature
["Season Temperatures"]
	Summer = [0.4, 0.7, 0.4]
	Autumn = [0.2, 0, -0.2]
	Winter = [-0.4, -0.7, -0.4]
	Spring = [-0.2, 0, 0.2]

