version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: 4G
    ports:
      - 25565:25565
    volumes:
      - ./data:/data

volumes:
  data:
