version: '3'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloudpassword
    volumes:
      - db:/var/lib/mysql
  app:
    image: nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloudpassword
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=adminpassword
    ports:
      - 8080:80
    command: chown www-data /var/www/html/config/config.php
    volumes:
      - ./config.php:/var/www/html/config/config.php
      - nextcloud:/var/www/html
    depends_on:
      - db
volumes:
  db:
  nextcloud:
